let user = {
  name: "Anurag",
  username: "asingh",
  email: "asingh@radicleinc.com",
  token: "abcdfefcdhvh5673ejnh3g",
  permissions: {},
  panels: {
    p1: {
      name: "First",
      id: "p1",
      archived: false,
      color: "#dgfdgd",
      url: "/panels/p1",
      dataSources: [
        { id: "sgh", name: "Gmail" },
        { id: "sgh", name: "OneDrive" },
        { id: "sgh", name: "Slack" },
        { id: "sgh", name: "Outlook" },
        { id: "sgh", name: "Drive" },
      ],
      children: [{}],
    },
    p2: {
      name: "First",
      id: "p2",
      archived: false,
      color: "#dgfdgd",
      url: "/panels/p2",
      dataSources: [],
      children: [
        {
          name: "Child1",
          id: "c1",
          pId:'p2',
          archived: false,
          color: "#dgfdgd",
          url: "/panels/p2/subpanel/c1",
          dataSources: [
            { id: "sgh", name: "Gmail" },
            { id: "sgh", name: "OneDrive" },
          ],
        },
        {
          name: "Child2",
          id: "c2",
          pId:'p2',
          archived: false,
          color: "#dgfdgd",
          url: "/panels/p2/subpanel/c2",
          dataSources: [
            { id: "sgh", name: "Gmail" },
            { id: "sgh", name: "Slack" },
          ],
        },
        {
          name: "Child3",
          id: "c3",
          pId:'p2',
          archived: false,
          color: "#dgfdgd",
          url: "/panels/p2/subpanel/c3",
          dataSources: [
            { id: "sgh", name: "Slack" },
            { id: "sgh", name: "OneDrive" },
          ],
        },
      ],
    },
    p3: {
      name: "First",
      id: "p3",
      archived: false,
      color: "#dgfdgd",
      url: "/panels/p3",
      dataSources: [
        { id: "sgh", name: "Gmail" },
        { id: "sgh", name: "OneDrive" },
        { id: "sgh", name: "Slack" },
        { id: "sgh", name: "Outlook" },
        { id: "sgh", name: "Drive" },
      ],
      children: [{}],
    },
    p4: {
      name: "First",
      id: "p4",
      archived: false,
      color: "#dgfdgd",
      url: "/panels/p4",
      dataSources: [
        { id: "sgh", name: "Gmail" },
        { id: "sgh", name: "OneDrive" },
        { id: "sgh", name: "Slack" },
        { id: "sgh", name: "Outlook" },
        { id: "sgh", name: "Drive" },
      ],
      children: [{}],
    },
    p11: {
      name: "First",
      id: "p11",
      archived: true,
      color: "#dgfdgd",
      url: "/panels/p11",
      dataSources: [
        { id: "sgh", name: "Gmail" },
        { id: "sgh", name: "OneDrive" },
        { id: "sgh", name: "Slack" },
        { id: "sgh", name: "Outlook" },
        { id: "sgh", name: "Drive" },
      ],
      children: [{}],
    },
    p12: {
      name: "First",
      id: "p12",
      archived: true,
      color: "#dgfdgd",
      url: "/panels/p12",
      dataSources: [],
      children: [
        {
          name: "Child11",
          id: "c11",
          pId:'p12',
          archived: true,
          color: "#dgfdgd",
          url: "/panels/p12/subpanel/c11",
          dataSources: [
            { id: "sgh", name: "Gmail" },
            { id: "sgh", name: "OneDrive" },
          ],
        },
        {
          name: "Child12",
          id: "c12",
          pId:'p12',
          archived: true,
          color: "#dgfdgd",
          url: "/panels/p12/subpanel/c12",
          dataSources: [
            { id: "sgh", name: "Gmail" },
            { id: "sgh", name: "Slack" },
          ],
        },
        {
          name: "Child13",
          id: "c13",
          pId:'p12',
          archived: true,
          color: "#dgfdgd",
          url: "/panels/p12/subpanel/c13",
          dataSources: [
            { id: "sgh", name: "Slack" },
            { id: "sgh", name: "OneDrive" },
          ],
        },
      ],
    },
  },
};

export default user;
